/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh token */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout user */
        post: operations["logoutUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List cities */
        get: operations["listCities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/niches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List niches */
        get: operations["listNiches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List product plans */
        get: operations["listProductPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List companies */
        get: operations["listCompanies"];
        put?: never;
        /** Create company */
        post: operations["createCompany"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{companyId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        /** Get company by ID */
        get: operations["getCompany"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update company */
        patch: operations["updateCompany"];
        trace?: never;
    };
    "/claims/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search claim candidates */
        get: operations["listClaimCandidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claims/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a claim request */
        post: operations["createClaimRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claims/cnpj/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm card CNPJ sent via WhatsApp */
        post: operations["confirmClaimCnpj"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/serpapi/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start SerpAPI import */
        post: operations["startSerpapiImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List companies (admin) */
        get: operations["listAdminCompanies"];
        put?: never;
        /** Create company (admin) */
        post: operations["createAdminCompany"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/companies/{companyId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        /** Get company (admin) */
        get: operations["getAdminCompany"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update company (admin) */
        patch: operations["updateAdminCompany"];
        trace?: never;
    };
    "/admin/companies/{companyId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update company status (admin) */
        patch: operations["updateAdminCompanyStatus"];
        trace?: never;
    };
    "/admin/serpapi/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List SerpAPI runs */
        get: operations["listSerpapiRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/serpapi/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        /** Get run detail */
        get: operations["getSerpapiRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/serpapi/runs/{runId}/records": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        /** List records for a SerpAPI run */
        get: operations["listSerpapiRunRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/serpapi/runs/{runId}/resolve-conflict": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve a conflict record */
        post: operations["resolveSerpapiConflict"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/serpapi/runs/{runId}/records/{recordId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
                recordId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish a SerpAPI record as company */
        post: operations["publishSerpapiRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/serpapi/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export SerpAPI data */
        get: operations["exportSerpapi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{companyId}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim company */
        post: operations["claimCompany"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{companyId}/channels": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update company channels */
        patch: operations["updateCompanyChannels"];
        trace?: never;
    };
    "/auction/configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List auction configs */
        get: operations["listAuctionConfigs"];
        put?: never;
        /** Upsert auction config */
        post: operations["saveAuctionConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auction/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get slot overview */
        get: operations["getAuctionSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get wallet */
        get: operations["getWallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List billing transactions */
        get: operations["listBillingTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/recharge-intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create recharge intent */
        post: operations["createRechargeIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/purchase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Purchase billing credits */
        post: operations["purchaseBillingCredits"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get subscription */
        get: operations["getSubscription"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/subscriptions/{companyId}/downgrade": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Schedule subscription downgrade */
        post: operations["scheduleSubscriptionDowngrade"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/payment-methods/{companyId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register payment method */
        post: operations["registerPaymentMethod"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/payment-methods/{companyId}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke payment method */
        delete: operations["revokePaymentMethod"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Company search */
        post: operations["searchCompanies"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Public company search (resolve city/niche by name) */
        post: operations["publicSearchCompanies"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/{searchId}/click": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                searchId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log click */
        post: operations["logClick"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/{searchId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                searchId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Track search events */
        post: operations["trackSearchEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Product search via query params */
        get: operations["searchProductsByQuery"];
        put?: never;
        /** Product search */
        post: operations["searchProducts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/searches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search analytics */
        get: operations["getSearchAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard KPIs */
        get: operations["getAnalyticsDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{companyId}/product-subscription": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        /** Get product subscription */
        get: operations["getCompanySubscription"];
        put?: never;
        /** Set product subscription */
        post: operations["setCompanySubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{companyId}/product-offers": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        /** List product offers */
        get: operations["listCompanyOffers"];
        put?: never;
        /** Create product offer */
        post: operations["createCompanyOffer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{companyId}/product-offers/{offerId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
                offerId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update product offer */
        patch: operations["updateCompanyOffer"];
        trace?: never;
    };
    "/integrations/whatsapp/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Webhook de mensagens do WhatsApp
         * @description Endpoint chamado pelo WhatsApp Cloud API. Valida WHATSAPP_WEBHOOK_SECRET (header x-webhook-secret) e faz dedupe por messageId. Outbound depende de WHATSAPP_PROVIDER (generic|meta).
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Shared secret for webhook authentication */
                    "x-webhook-secret": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WhatsappWebhookPayload"];
                };
            };
            responses: {
                /** @description Webhook processed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
                /** @description Invalid payload */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid webhook token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/r/w/{searchId}/{companyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Redirect para WhatsApp com tracking
         * @description Endpoint publico de redirect: registra click_whatsapp e redireciona para wa.me. Usa PUBLIC_BASE_URL nos links gerados.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    searchId: string;
                    companyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to wa.me */
                302: {
                    headers: {
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing company phone/whatsapp */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid searchId/companyId */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/r/c/{searchId}/{companyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Redirect para ligacao com tracking
         * @description Endpoint publico de redirect: registra click_call e redireciona para tel:. Usa PUBLIC_BASE_URL nos links gerados.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    searchId: string;
                    companyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to tel: */
                302: {
                    headers: {
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing company phone/whatsapp */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid searchId/companyId */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics (admin-only)
         * @description Não expor publicamente
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Metrics payload (JSON with snapshot) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API health check (internal)
         * @description Não expor publicamente
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Health status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status: string;
                            uptime: number;
                            timestamp: string;
                            version: string;
                            services: {
                                database: string;
                                whatsapp_webhook: string;
                                whatsapp_api: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            id: string;
            email: string;
            name: string;
            /** @enum {string} */
            role?: "admin" | "owner";
            /** Format: date-time */
            createdAt?: string;
        };
        City: {
            id: string;
            name: string;
            state: string;
            isActive?: boolean;
        };
        Niche: {
            id: string;
            label: string;
            slug: string;
            isActive?: boolean;
        };
        AuthLoginInput: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthRefreshInput: {
            refreshToken: string;
        };
        AuthLoginResponse: {
            accessToken?: string;
            refreshToken?: string;
            user?: components["schemas"]["User"];
        };
        AuthRefreshResponse: {
            accessToken?: string;
        };
        AuthLogoutRequest: {
            refreshToken?: string;
        };
        AuthLogoutResponse: {
            success: boolean;
        };
        CompanyChannels: {
            phone?: string;
            whatsapp?: string;
            address?: string;
            latitude?: number;
            longitude?: number;
            openingHours?: string;
        };
        Company: {
            id: string;
            tradeName: string;
            legalName?: string | null;
            cityId?: string;
            ownerId?: string;
            /** @enum {string} */
            origin?: "serpapi" | "manual" | "claimed";
            qualityScore?: number;
            city?: components["schemas"]["City"];
            niches?: {
                id?: string;
                label?: string;
                slug?: string;
                isActive?: boolean;
            }[];
            /** @enum {string} */
            status?: "draft" | "pending" | "active" | "suspended";
            channels?: components["schemas"]["CompanyChannels"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        AdminCompany: {
            id: string;
            name: string;
            cityId: string;
            nicheId: string;
            addressLine: string;
            phoneE164?: string | null;
            whatsappE164?: string | null;
            website?: string | null;
            lat?: string | null;
            lng?: string | null;
            /** @enum {string} */
            status: "draft" | "pending" | "active" | "suspended";
            /** @enum {string} */
            origin: "serpapi" | "manual" | "claimed";
            qualityScore: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        AdminCompanyCreateInput: {
            name: string;
            cityId: string;
            nicheId: string;
            addressLine: string;
            phoneE164?: string;
            whatsappE164?: string;
            website?: string;
            lat?: number;
            lng?: number;
            /** @enum {string} */
            status?: "draft" | "pending" | "active" | "suspended";
            /** @enum {string} */
            origin?: "serpapi" | "manual" | "claimed";
            force?: boolean;
        };
        AdminCompanyUpdateInput: {
            name?: string;
            cityId?: string;
            nicheId?: string;
            addressLine?: string;
            phoneE164?: string;
            whatsappE164?: string;
            website?: string;
            lat?: number;
            lng?: number;
            /** @enum {string} */
            status?: "draft" | "pending" | "active" | "suspended";
            /** @enum {string} */
            origin?: "serpapi" | "manual" | "claimed";
            force?: boolean;
        };
        AdminCompanyStatusInput: {
            /** @enum {string} */
            status: "draft" | "pending" | "active" | "suspended";
        };
        AdminCompaniesResponse: {
            items: components["schemas"]["AdminCompany"][];
            total: number;
            page: number;
            limit: number;
        };
        DedupeHit: {
            id: string;
            name: string;
            addressLine?: string | null;
            phoneE164?: string | null;
            whatsappE164?: string | null;
            website?: string | null;
            status: string;
            cityId: string;
        };
        DedupeConflictResponse: {
            message: string;
            dedupeHits: components["schemas"]["DedupeHit"][];
        };
        SerpapiPublishRequest: {
            /** @enum {string} */
            statusAfter?: "pending" | "active";
            force?: boolean;
            targetCompanyId?: string;
        };
        SerpapiPublishResponse: {
            companyId: string;
            /** @enum {string} */
            mode: "created" | "linked";
        };
        SerpapiImportRequest: {
            cityId: string;
            nicheId: string;
            query?: string;
            limit?: number;
            dryRun?: boolean;
        };
        SerpapiRunSummary: {
            id: string;
            status: string;
            cityId?: string;
            nicheId?: string;
            query?: string;
            found?: number;
            inserted?: number;
            updated?: number;
            conflicts?: number;
            errors?: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            finishedAt?: string;
        };
        SerpapiRecordItem: {
            id: string;
            /** @enum {string} */
            status: "inserted" | "updated" | "conflict" | "error" | "ignored";
            companyId?: string;
            dedupeKey?: string;
            reason?: string;
            /** @description Sanitized preview (JSON of title/name/address/website truncated to 2000 chars) */
            rawPreview?: string;
        };
        SerpapiRunDetail: {
            run: components["schemas"]["SerpapiRunSummary"];
            records: {
                items: components["schemas"]["SerpapiRecordItem"][];
                total: number;
            };
        };
        SerpapiRecordsResponse: {
            items: components["schemas"]["SerpapiRecordItem"][];
            total: number;
            limit: number;
            offset: number;
        };
        ResolveConflictRequest: {
            recordId: string;
            /** @enum {string} */
            action: "link_existing" | "create_new" | "ignore";
            companyId?: string;
        };
        CompanyCreateInput: {
            tradeName: string;
            legalName?: string;
            cityId: string;
            nicheIds?: string[];
            channels?: components["schemas"]["CompanyChannels"];
        };
        CompanyUpdateInput: {
            tradeName?: string;
            legalName?: string;
            nicheIds?: string[];
        };
        CompanyClaimInput: {
            /** @enum {string} */
            proofType: "sms" | "email" | "document";
            proofValue: string;
        };
        PaginatedCompanies: {
            items: components["schemas"]["Company"][];
            total: number;
            page: number;
            pageSize: number;
        };
        AuctionBids: {
            position1?: number;
            position2?: number;
            position3?: number;
        };
        AuctionConfig: {
            id: string;
            companyId: string;
            cityId: string;
            nicheId: string;
            /** @enum {string} */
            mode?: "manual" | "smart" | "auto";
            bids?: components["schemas"]["AuctionBids"];
            targetPosition?: 1 | 2 | 3;
            /** @enum {string} */
            targetShare?: "one_in_3" | "one_in_5" | "one_in_10";
            dailyBudget?: number;
            pauseOnLimit?: boolean;
            isActive?: boolean;
        };
        AuctionConfigInput: {
            companyId: string;
            cityId: string;
            nicheId: string;
            /** @enum {string} */
            mode: "manual" | "smart" | "auto";
            bids?: components["schemas"]["AuctionBids"];
            targetPosition?: 1 | 2 | 3;
            /** @enum {string} */
            targetShare?: "one_in_3" | "one_in_5" | "one_in_10";
            dailyBudget?: number;
            pauseOnLimit?: boolean;
            isActive?: boolean;
        };
        AuctionSlot: {
            position: number;
            company?: components["schemas"]["Company"];
            currentBid?: number;
        };
        AuctionSlotOverview: {
            cityId?: string;
            nicheId?: string;
            slots?: components["schemas"]["AuctionSlot"][];
        };
        Wallet: {
            balance: number;
            reserved: number;
            currency: string;
        };
        Transaction: {
            id: string;
            companyId: string;
            /** @enum {string} */
            type: "credit" | "debit" | "search_debit" | "recharge" | "wallet_debit" | "subscription_renewal" | "subscription_failed";
            amount: number;
            amountCents?: number;
            /** @enum {string} */
            status?: "pending" | "confirmed" | "failed" | "cancelled";
            reason?: string;
            provider?: string | null;
            externalId?: string | null;
            subscriptionId?: string | null;
            /** Format: date-time */
            periodStart?: string | null;
            /** Format: date-time */
            periodEnd?: string | null;
            metadata?: Record<string, never> | null;
            /** Format: date-time */
            occurredAt?: string;
        };
        RechargeIntent: {
            id: string;
            amount: number;
            method?: string;
            status?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        BillingRechargeIntentInput: {
            companyId: string;
            amount: number;
            /** @enum {string} */
            method?: "pix" | "credit_card" | "boleto";
        };
        SearchRequest: {
            query?: string;
            cityId: string;
            nicheId: string;
            lat?: number;
            lng?: number;
            /** @enum {string} */
            source?: "whatsapp" | "web" | "demo";
        };
        PublicSearchRequest: {
            text: string;
            city: string;
            niche?: string;
            /** @description Max 7 results */
            limit?: number;
        };
        SearchResult: {
            company?: components["schemas"]["Company"];
            rank: number;
            position: number;
            isPaid: boolean;
            chargedAmount?: number;
            clickTrackingId?: string;
        };
        OfferedBy: {
            text: string;
            imageUrl?: string;
            website?: string;
            promotionsUrl?: string;
            phoneE164?: string;
            whatsappE164?: string;
            configId?: string;
            companyId?: string;
        };
        SearchResponse: {
            searchId: string;
            results: components["schemas"]["SearchResult"][];
            offeredBy?: components["schemas"]["OfferedBy"];
        };
        SearchClickInput: {
            companyId: string;
            /** @enum {string} */
            channelType: "phone" | "whatsapp";
        };
        SearchEventInput: {
            /** @enum {string} */
            type: "impression" | "click_whatsapp" | "click_call";
            companyId?: string;
        };
        ProductPlan: {
            id: string;
            name: string;
            description?: string;
            monthlyPriceCents: number;
            maxActiveOffers: number;
            isActive?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Subscription: {
            id: string;
            companyId: string;
            planId: string;
            /** @enum {string} */
            status: "active" | "past_due" | "cancelled";
            /** Format: date-time */
            currentPeriodStart: string;
            /** Format: date-time */
            currentPeriodEnd: string;
            /** Format: date-time */
            graceUntil?: string | null;
            scheduledPlanId?: string | null;
            /** @enum {string|null} */
            paymentMethod?: "card" | "wallet" | null;
            plan?: components["schemas"]["ProductPlan"];
        };
        PaymentMethod: {
            id: string;
            companyId: string;
            /** @enum {string} */
            provider: "stripe" | "pagarme" | "mercadopago" | "dummy";
            customerId: string;
            paymentMethodId: string;
            /** @enum {string} */
            status: "active" | "revoked";
            last4?: string | null;
            brand?: string | null;
            expMonth?: number | null;
            expYear?: number | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        PaymentMethodCreateInput: {
            /** @enum {string} */
            provider: "stripe" | "pagarme" | "mercadopago" | "dummy";
            customerId: string;
            paymentMethodId: string;
            last4?: string;
            brand?: string;
            expMonth?: number;
            expYear?: number;
        };
        ProductSubscriptionBody: {
            planId: string;
        };
        ProductOffer: {
            id: string;
            companyId: string;
            cityId: string;
            nicheId: string;
            title: string;
            description?: string;
            priceCents: number;
            originalPriceCents?: number | null;
            isActive?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ProductSearchResult: {
            id: string;
            title: string;
            priceCents: number;
            /** Format: date-time */
            validUntil?: string;
            company: {
                id: string;
                name?: string;
                phone?: string;
                address?: string;
            };
            city: {
                id: string;
                name?: string;
            };
            source: "product";
        };
        ProductOfferCreateInput: {
            cityId: string;
            nicheId: string;
            title: string;
            description: string;
            priceCents: number;
            originalPriceCents?: number | null;
            isActive?: boolean;
        };
        ProductOfferUpdateInput: {
            title?: string;
            description?: string;
            priceCents?: number;
            originalPriceCents?: number | null;
            isActive?: boolean;
        };
        PaginatedProductOffers: {
            items: components["schemas"]["ProductOffer"][];
            total: number;
            page: number;
            pageSize: number;
        };
        ProductSearchRequest: {
            cityId: string;
            nicheId?: string;
            query?: string;
            limit?: number;
        };
        ProductSearchResponse: {
            items: components["schemas"]["ProductSearchResult"][];
            total: number;
        };
        ClaimCandidate: {
            companyId: string;
            nome: string;
            cityId: string;
            serpPhoneMasked: string;
            /** @enum {string} */
            matchReason: "both" | "phone" | "name";
        };
        ClaimRequestInput: {
            companyId: string;
            phone: string;
        };
        ClaimRequestResponse: {
            requestId: string;
            /** @enum {string} */
            method: "whatsapp_otp" | "cnpj_whatsapp";
            next: {
                /** @enum {string} */
                type: "otp" | "cnpj_whatsapp";
                message: string;
                supportWhatsapp?: string;
            };
        };
        ClaimCnpjConfirmInput: {
            requestId: string;
            message?: string;
        };
        ClaimCnpjConfirmResponse: {
            success: boolean;
            next: {
                /** @enum {string} */
                type: "cnpj_whatsapp";
                supportWhatsapp: string;
                message: string;
            };
        };
        BillingPurchaseRequest: {
            amountCents: number;
            description?: string;
            plano?: string;
        };
        BillingPurchaseResponse: {
            success: boolean;
            balanceCents: number;
        };
        AnalyticsDashboardMoment: {
            appearancesToday: number;
            contactsToday: number;
            costPerContactToday: number;
            creditsSpentToday: number;
            currentPositionMainNiche?: number | null;
        };
        AnalyticsDashboardPeriodTopNiche: {
            nicheId: string;
            niche: string;
            total: number;
        };
        AnalyticsDashboardPeriod: {
            impressions: number;
            contacts: number;
            totalSpent: number;
            realImpressions?: number;
            realClicks?: number;
            realClicksWhatsapp?: number;
            realClicksCall?: number;
            realCtr?: number;
            /** @description Admin-only. Returns top companies by click volume. */
            topCompaniesByClick?: {
                companyId: string;
                name: string;
                total: number;
            }[];
            bestDayOfWeek?: string | null;
            bestHour?: string | null;
            topNiche?: components["schemas"]["AnalyticsDashboardPeriodTopNiche"];
        };
        AnalyticsDashboardNiche: {
            nicheId: string;
            nicheName: string;
            positionToday?: number | null;
            iecToday: number;
            impressionsToday: number;
            contactsToday: number;
            activeReserve: number;
        };
        AnalyticsDashboardResponse: {
            moment: components["schemas"]["AnalyticsDashboardMoment"];
            period: components["schemas"]["AnalyticsDashboardPeriod"];
            niches: components["schemas"]["AnalyticsDashboardNiche"][];
        };
        SearchAnalyticsItem: {
            searchId: string;
            /** Format: date-time */
            createdAt: string;
            city: string;
            niche: string;
            query: string;
            totalResults: number;
            paidResults: number;
            organicResults: number;
            totalCharged: number;
            hasClicks: boolean;
        };
        SearchAnalyticsResponse: {
            items: components["schemas"]["SearchAnalyticsItem"][];
            total: number;
            page: number;
            pageSize: number;
        };
        CitiesQuery: {
            q?: string;
        };
        NichesQuery: {
            cityId?: string;
        };
        CompaniesQuery: {
            q?: string;
            cityId?: string;
            nicheId?: string;
            /** @enum {string} */
            status?: "pending" | "active" | "suspended";
        };
        CompanyIdParam: {
            companyId: string;
        };
        CompanyChannelsInput: {
            phone?: string;
            whatsapp?: string;
            address?: string;
            latitude?: number;
            longitude?: number;
            openingHours?: string;
        };
        AuctionConfigQuery: {
            companyId?: string;
            cityId?: string;
            nicheId?: string;
        };
        AuctionSlotQuery: {
            cityId: string;
            nicheId: string;
        };
        BillingTransactionsQuery: {
            companyId: string;
            /** Format: date-time */
            from?: string;
            /** Format: date-time */
            to?: string;
        };
        SearchAnalyticsQuery: {
            /** Format: date-time */
            from?: string;
            /** Format: date-time */
            to?: string;
            cityId?: string;
            nicheId?: string;
            companyId?: string;
            page?: number;
            pageSize?: number;
        };
        ProductOffersQuery: {
            page?: number;
            pageSize?: number;
        };
        SearchClickParams: {
            searchId: string;
        };
        WhatsappWebhookPayload: {
            object: string;
            entry: {
                id?: string;
                changes?: {
                    value?: {
                        messages?: {
                            from?: string;
                            id?: string;
                            timestamp?: string;
                            type?: string;
                            text?: {
                                body?: string;
                            };
                        }[];
                        metadata?: {
                            phone_number_id?: string;
                        };
                    };
                }[];
            }[];
        };
        WhatsappInboundMessage: {
            from: string;
            phoneNumberId: string;
            messageId: string;
            text: string;
        };
        WhatsappOutboundMessage: {
            to: string;
            phoneNumberId: string;
            body: string;
        };
        HealthResponse: {
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLoginInput"];
            };
        };
        responses: {
            /** @description Auth tokens + user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthLoginResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRefreshInput"];
            };
        };
        responses: {
            /** @description New access token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthRefreshResponse"];
                };
            };
        };
    };
    logoutUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AuthLogoutRequest"];
            };
        };
        responses: {
            /** @description Token invalidated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid credentials or missing token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCities: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of cities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["City"][];
                };
            };
        };
    };
    listNiches: {
        parameters: {
            query?: {
                cityId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of niches */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Niche"][];
                };
            };
        };
    };
    listProductPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available plans */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductPlan"][];
                };
            };
        };
    };
    listCompanies: {
        parameters: {
            query?: {
                q?: string;
                cityId?: string;
                nicheId?: string;
                status?: "pending" | "active" | "suspended";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated companies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCompanies"];
                };
            };
        };
    };
    createCompany: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyCreateInput"];
            };
        };
        responses: {
            /** @description Created company */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
        };
    };
    getCompany: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Company */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
        };
    };
    updateCompany: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyUpdateInput"];
            };
        };
        responses: never;
    };
    listClaimCandidates: {
        parameters: {
            query: {
                cityId: string;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Potential company matches */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimCandidate"][];
                };
            };
        };
    };
    createClaimRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimRequestInput"];
            };
        };
        responses: {
            /** @description Claim tracking handle */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimRequestResponse"];
                };
            };
        };
    };
    confirmClaimCnpj: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimCnpjConfirmInput"];
            };
        };
        responses: {
            /** @description Instruction to send CNPJ to support */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimCnpjConfirmResponse"];
                };
            };
        };
    };
    startSerpapiImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SerpapiImportRequest"];
            };
        };
        responses: {
            /** @description Import run queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        runId?: string;
                    };
                };
            };
        };
    };
    listAdminCompanies: {
        parameters: {
            query?: {
                cityId?: string;
                nicheId?: string;
                status?: "draft" | "pending" | "active" | "suspended";
                q?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Companies list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCompaniesResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createAdminCompany: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCompanyCreateInput"];
            };
        };
        responses: {
            /** @description Company created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCompany"];
                };
            };
            /** @description Invalid payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dedupe conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DedupeConflictResponse"];
                };
            };
        };
    };
    getAdminCompany: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Company detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCompany"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Company not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAdminCompany: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCompanyUpdateInput"];
            };
        };
        responses: {
            /** @description Company updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCompany"];
                };
            };
            /** @description Invalid payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Company not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dedupe conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DedupeConflictResponse"];
                };
            };
        };
    };
    updateAdminCompanyStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCompanyStatusInput"];
            };
        };
        responses: {
            /** @description Status updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                    };
                };
            };
            /** @description Invalid status */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Company not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listSerpapiRuns: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SerpapiRunSummary"][];
                };
            };
        };
    };
    getSerpapiRun: {
        parameters: {
            query?: {
                status?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SerpapiRunDetail"];
                };
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listSerpapiRunRecords: {
        parameters: {
            query?: {
                status?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Records list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SerpapiRecordsResponse"];
                };
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resolveSerpapiConflict: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveConflictRequest"];
            };
        };
        responses: {
            /** @description Conflict resolved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                    };
                };
            };
        };
    };
    publishSerpapiRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
                recordId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SerpapiPublishRequest"];
            };
        };
        responses: {
            /** @description Published company */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SerpapiPublishResponse"];
                };
            };
            /** @description Invalid payload or status */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Run/record not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dedupe conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DedupeConflictResponse"];
                };
            };
        };
    };
    exportSerpapi: {
        parameters: {
            query: {
                runId: string;
                type: "runs" | "records" | "conflicts" | "companies";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV export */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
        };
    };
    claimCompany: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyClaimInput"];
            };
        };
        responses: {
            /** @description Claim response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                    };
                };
            };
        };
    };
    updateCompanyChannels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyChannels"];
            };
        };
        responses: {
            /** @description Channel update response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                    };
                };
            };
        };
    };
    listAuctionConfigs: {
        parameters: {
            query?: {
                companyId?: string;
                cityId?: string;
                nicheId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Auction configs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuctionConfig"][];
                };
            };
        };
    };
    saveAuctionConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuctionConfigInput"];
            };
        };
        responses: {
            /** @description Saved config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuctionConfig"];
                };
            };
        };
    };
    getAuctionSlots: {
        parameters: {
            query: {
                cityId: string;
                nicheId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Slot info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuctionSlotOverview"];
                };
            };
        };
    };
    getWallet: {
        parameters: {
            query?: {
                companyId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wallet */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wallet"];
                };
            };
        };
    };
    listBillingTransactions: {
        parameters: {
            query?: {
                companyId?: string;
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transactions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"][];
                };
            };
        };
    };
    createRechargeIntent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BillingRechargeIntentInput"];
            };
        };
        responses: {
            /** @description Recharge intent */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RechargeIntent"];
                };
            };
        };
    };
    purchaseBillingCredits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BillingPurchaseRequest"];
            };
        };
        responses: {
            /** @description Purchase result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingPurchaseResponse"];
                };
            };
            /** @description Invalid payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSubscription: {
        parameters: {
            query?: {
                companyId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            /** @description Subscription not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    scheduleSubscriptionDowngrade: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    planId: string;
                };
            };
        };
        responses: {
            /** @description Scheduled downgrade */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            /** @description Subscription not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    registerPaymentMethod: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentMethodCreateInput"];
            };
        };
        responses: {
            /** @description Payment method created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentMethod"];
                };
            };
        };
    };
    revokePaymentMethod: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment method revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentMethod"];
                };
            };
            /** @description Payment method not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    searchCompanies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    publicSearchCompanies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicSearchRequest"];
            };
        };
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Invalid payload or city not found */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logClick: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                searchId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchClickInput"];
            };
        };
        responses: {
            /** @description OK */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    trackSearchEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                searchId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchEventInput"];
            };
        };
        responses: {
            /** @description OK */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Search not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    searchProductsByQuery: {
        parameters: {
            query?: {
                query?: string;
                cityId?: string;
                nicheId?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSearchResponse"];
                };
            };
        };
    };
    searchProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductSearchRequest"];
            };
        };
        responses: {
            /** @description Product search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSearchResponse"];
                };
            };
        };
    };
    getSearchAnalytics: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                cityId?: string;
                nicheId?: string;
                companyId?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Analytics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchAnalyticsResponse"];
                };
            };
        };
    };
    getAnalyticsDashboard: {
        parameters: {
            query?: {
                companyId?: string;
                from?: string;
                to?: string;
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsDashboardResponse"];
                };
            };
            /** @description Missing or invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCompanySubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
        };
    };
    setCompanySubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductSubscriptionBody"];
            };
        };
        responses: {
            /** @description Updated subscription */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
        };
    };
    listCompanyOffers: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Offers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProductOffers"];
                };
            };
        };
    };
    createCompanyOffer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductOfferCreateInput"];
            };
        };
        responses: {
            /** @description Created offer */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOffer"];
                };
            };
        };
    };
    updateCompanyOffer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
                offerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductOfferUpdateInput"];
            };
        };
        responses: {
            /** @description Updated offer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOffer"];
                };
            };
        };
    };
}





